services:
  fphl-django:
    container_name: django
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app/fphlcore/
      - media:/app/fphlcore/media
      - static:/app/fphlcore/staticroot
      - db:/app/fphlcore/
    networks:
      - site-network
  nginx:
    container_name: nginx
    depends_on:
      - fphl-django
    image: nginx:1.27.0-alpine
    networks:
      - site-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - media:/app/fphlcore/media
      - static:/app/fphlcore/staticroot
networks:
  site-network:
    driver: bridge
volumes:
  db:
  media:
  static: